//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KisanMitraFinal
{
    using System;
    using System.Collections.Generic;
    
    public partial class CropForSell
    {
        public int csid { get; set; }
        public string farmername { get; set; }
        public long mobilenumber { get; set; }
        public string fstate { get; set; }
        public string district { get; set; }
        public string block { get; set; }
        public string commodity { get; set; }
        public string season { get; set; }
        public double amountOfCommodity { get; set; }
    }
}
