//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KisanMitraFinal
{
    using System;
    using System.Collections.Generic;
    
    public partial class CropPrice
    {
        public int cid { get; set; }
        public string commodity { get; set; }
        public string season { get; set; }
        public string cstate { get; set; }
        public string district { get; set; }
        public string block { get; set; }
        public decimal currentPrice { get; set; }
    }
}
