//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KisanMitraFinal
{
    using System;
    using System.Collections.Generic;
    
    public partial class FarmerDetail
    {
        public string farmername { get; set; }
        public long mobilenumber { get; set; }
        public string fstate { get; set; }
        public string district { get; set; }
        public string block { get; set; }
        public int age { get; set; }
        public string gender { get; set; }
        public string username { get; set; }
        public string fpassword { get; set; }
    }
}
