//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KisanMitraFinal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KisanMitraDBEntities1 : DbContext
    {
        public KisanMitraDBEntities1()
            : base("name=KisanMitraDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CropForSell> CropForSells { get; set; }
        public virtual DbSet<CropPrice> CropPrices { get; set; }
        public virtual DbSet<FarmerDetail> FarmerDetails { get; set; }
        public virtual DbSet<MerchantDetail> MerchantDetails { get; set; }
    }
}
