//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KisanMitraFinal
{
    using System;
    using System.Collections.Generic;
    
    public partial class MerchantDetail
    {
        public string merchantname { get; set; }
        public long mobilenumber { get; set; }
        public string address { get; set; }
        public string mstate { get; set; }
        public string district { get; set; }
        public string block { get; set; }
        public int age { get; set; }
        public string gender { get; set; }
        public string username { get; set; }
        public string mpassword { get; set; }
    }
}
